---
kind: pipeline
type: exec
name: default
concurrency:
  limit: 1
  
clone:
  disable: true

steps:
- name: refresh
  commands:
  - eval `ssh-agent -s`
  - ssh-add /home/dreamland/.ssh/drone
  - cd /home/dreamland/runtime/share/DL
  - git add .
  - git commit -m 'Latest changes from hosting' || echo 'No changes to commit'
  - git pull --rebase
  - git push
  - kill $SSH_AGENT_PID
 - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message:  >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
