---
kind: pipeline
type: exec
name: default
concurrency:
  limit: 1
  
clone:
  disable: true

steps:
- name: refresh
  commands:
  - eval `ssh-agent -s`
  - ssh-add /home/dreamland/.ssh/drone
  - cd /home/dreamland/runtime/share/DL
  - git add .
  - git commit -m 'Latest changes from hosting' || echo 'No changes to commit'
  - git pull --rebase
  - git push
  - kill $SSH_AGENT_PID
