---
kind: pipeline
type: exec
name: default
concurrency:
  limit: 1
  
clone:
  disable: true

steps:
- name: refresh
  commands:
  - eval `ssh-agent -s`
  - ssh-add /home/dreamland/.ssh/drone
  - cd /home/dreamland/runtime/share/DL
  - git add .
  - git commit -m 'Latest changes from hosting' || echo 'No changes to commit'
  - git pull --rebase
  - git push
  - kill $SSH_AGENT_PID
  
- name: discord_failure
  commands:
  - >
    echo "{\"embeds\":[{\"color\": 13632027,\"description\":\"Latest dreamland_world failed to merge, please resolve conflicts to continue\n\",\"title\":\"Deployment failed!\"}], \"username\":\"Drone Bot\", \"avatar_url\": \"https://docs.drone.io/logo.svg\"}" \
    | /home/dreamland/runtime/bin/idiscord-code
  when:
    status:
      - failure
  
- name: discord_success
  commands:
  - >
    echo "{\"embeds\":[{\"color\": 8311585,\"description\":\"Latest dreamland_world pulled successfully, reload plugins to apply\n\",\"title\":\"Deployment successful\"}], \"username\":\"Drone Bot\", \"avatar_url\": \"https://docs.drone.io/logo.svg\"}" \
    | /home/dreamland/runtime/bin/idiscord-code
  when:
    status:
      - success
